[aws]
disabled = true
format = '\[[$symbol($profile)(\($region\))(\[$duration\])]($style)\]'

[bun]
format = '\[[$symbol]($style)\]'

[c]
format = '\[[$symbol($version(-$name))]($style)\]'

[cmake]
format = '\[[$symbol]($style)\]'

[cmd_duration]
format = '\[[⏱ $duration]($style)\]'

[cobol]
format = '\[[$symbol]($style)\]'

[conda]
format = '\[[$symbol$environment]($style)\]'

[crystal]
format = '\[[$symbol]($style)\]'

[daml]
format = '\[[$symbol]($style)\]'

[dart]
format = '\[[$symbol]($style)\]'

[deno]
format = '\[[$symbol]($style)\]'

[docker_context]
format = '\[[$symbol$context]($style)\]'

[dotnet]
format = '\[[$symbol(🎯 $tfm)]($style)\]'

[elixir]
format = '\[[$symbol($version \(OTP $otp_version\))]($style)\]'

[elm]
format = '\[[$symbol]($style)\]'

[erlang]
symbol = "ⓔ "
format = '\[[$symbol]($style)\]'

[fennel]
format = '\[[$symbol]($style)\]'

[fossil_branch]
format = '\[[$symbol$branch]($style)\]'

[gcloud]
format = '\[[$symbol$account(@$domain)(\($region\))]($style)\]'

[git_branch]
format = '\[[$symbol$branch]($style)\]'

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'

[golang]
format = '\[[$symbol]($style)\]'

[gradle]
format = '\[[$symbol]($style)\]'

[guix_shell]
format = '\[[$symbol]($style)\]'

[haskell]
format = '\[[$symbol]($style)\]'

[haxe]
format = '\[[$symbol]($style)\]'

[helm]
format = '\[[$symbol]($style)\]'

[hg_branch]
format = '\[[$symbol$branch]($style)\]'

[java]
format = '\[[$symbol]($style)\]'

[julia]
format = '\[[$symbol]($style)\]'

[kotlin]
format = '\[[$symbol]($style)\]'

[kubernetes]
format = '\[[$symbol$context( \($namespace\))]($style)\]'

[lua]
format = '\[[$symbol]($style)\]'

[meson]
format = '\[[$symbol$project]($style)\]'

[nim]
format = '\[[$symbol]($style)\]'

[nix_shell]
format = '\[[$symbol$state( \($name\))]($style)\]'

[nodejs]
symbol = "[⬢](bold green) "
format = '\[[$symbol NodeJS]($style)\]'

[ocaml]
format = '\[[$symbol(\($switch_indicator$switch_name\))]($style)\]'

[opa]
format = '\[[$symbol]($style)\]'

[openstack]
format = '\[[$symbol$cloud(\($project\))]($style)\]'

[os]
format = '\[[$symbol]($style)\]'

[package]
disabled = true

[perl]
format = '\[[$symbol]($style)\]'

[php]
format = '\[[$symbol]($style)\]'

[pijul_channel]
format = '\[[$symbol$channel]($style)\]'

[pulumi]
symbol = "🧊 "
format = '\[[$symbol$stack]($style)\]'

[purescript]
format = '\[[$symbol]($style)\]'

[python]
format = '\[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\]'

[raku]
format = '\[[$symbol($version-$vm_version)]($style)\]'

[red]
format = '\[[$symbol]($style)\]'

[ruby]
format = '\[[$symbol]($style)\]'

[rust]
format = '\[[$symbol]($style)\]'

[scala]
format = '\[[$symbol]($style)\]'

[spack]
format = '\[[$symbol$environment]($style)\]'

[sudo]
format = '\[[as $symbol]($style)\]'

[swift]
format = '\[[$symbol]($style)\]'

[terraform]
format = '\[[$symbol$workspace]($style)\]'

[time]
format = '\[[$time]($style)\]'

[username]
format = '\[[$user]($style)\]'

[vagrant]
format = '\[[$symbol]($style)\]'

[vlang]
format = '\[[$symbol]($style)\]'

[zig]
format = '\[[$symbol]($style)\]'

[memory_usage]
disabled = false
threshold = -1
symbol = '● '
style = 'bold dimmed green'
format = '\[$symbol[$ram( | $swap)]($style)\]'

[battery]
disabled = false
full_symbol = "🔋 "
charging_symbol = "⚡️⇡ "
discharging_symbol = "⚡️⇣ "
unknown_symbol = "❓ "
empty_symbol = "❗ "

[[battery.display]]
threshold = 100
style = 'bold green'

[[battery.display]]
threshold = 50
style = 'bold yellow'

[[battery.display]]
threshold = 25
style = 'bold orange'

[[battery.display]]
threshold = 10
style = 'bold red'
